<?php

namespace ContainerD18jQCS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBasicTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\BasicType' shared autowired service.
     *
     * @return \App\Form\Type\BasicType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Flow/FormFlowTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Flow/AbstractFlowType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/BasicType.php';

        return $container->privates['App\\Form\\Type\\BasicType'] = new \App\Form\Type\BasicType();
    }
}
