<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD18jQCS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD18jQCS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD18jQCS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD18jQCS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD18jQCS\App_KernelDevDebugContainer([
    'container.build_hash' => 'D18jQCS',
    'container.build_id' => '4d44ee63',
    'container.build_time' => 1764574194,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD18jQCS');
